### ISSUE TITLE
Support appmetrics on Alpine linux Docker image

### ISSUE THREAD

**Issue by tomershvueliebsco** [RuntimeTools/appmetrics#454] opened 2017-06-13 20:07 UTC
We've been trying to integrate appmetrics into our Loopback (Node.js) application and have been having trouble when trying to start up the Docker image. 

This is the error we're getting:
```
return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error relocating /node_modules/appmetrics/appmetrics.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi: symbol not found
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/appmetrics/index.js:27:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

We are running this on Alpine but are able to install glibc through the Dockerfile.

**Comment by sam-github** [comment] 2017-06-13 21:55
Can you post your Dockerfile? and `node --version` where you build the docker image, and `node --version` from inside the docker image? It looks a bit like the architecture in the docker image (or node version?) isn't the one that app was npm installed with.

@rmg have you seen this?

**Comment by rmg** [comment] 2017-06-13 22:57
@sam-github sort of.. in a round about manner.

If I use an alpine base image and try to install `appmetrics` and then `require('appmetrics')` I get an error about missing glibc. If I hack the `package.json` to allow me to rebuild the addon from source (and install all the pre-reqs), I eventually get compile errors related to musl-libc having a different definition of `struct sigevent` (used by `src/plugins/node/prof/watchdog.h`).

The compilation errors at the end of this path are what I've seen before.

**Comment by rmg** [comment] 2017-06-13 22:58
For comparison, doing this with a glibc based image like `node:latest` works out of the box as expected.

**Comment by sam-github** [comment] 2017-06-14 03:47
@tomershvueliebsco it looks like Alpine will take some effort to support, could you use another base image? 

@tobespc may  want to rename the issue to an Alpine linux support feature request.

**Comment by tomershvueliebsco** [comment] 2017-06-14 13:15
@sam-github, this is our Dockerfile at the moment:
```
FROM node:7.4.0-alpine

RUN ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" && \
    ALPINE_GLIBC_PACKAGE_VERSION="2.25-r0" && \
    ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    apk add --no-cache --virtual=.build-dependencies wget ca-certificates && \
    wget \
        "https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/sgerrand.rsa.pub" \
        -O "/etc/apk/keys/sgerrand.rsa.pub" && \
    wget \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    apk add --no-cache \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    \
    rm "/etc/apk/keys/sgerrand.rsa.pub" && \
    /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true && \
    echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh && \
    \
    apk del glibc-i18n && \
    \
    rm "/root/.wget-hsts" && \
    apk del .build-dependencies && \
    rm \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"

ENV LANG=C.UTF-8

ADD ./ ./

ENTRYPOINT ["node", "."]
```
We got here by using a base image of Alpine that has Node already on it, and then installing the glibc package on top, based off of this Dockerfile: https://github.com/frol/docker-alpine-glibc/blob/master/Dockerfile

**Comment by nordluf** [comment] 2017-10-12 10:31
Are there any updates? We still have such problem with Alpine Linux

**Comment by sjanuary** [comment] 2017-10-12 11:16
@nordluf - I can't see us having time for this any time soon unfortunately due to other priorities, however appmetrics is open source and we are open to receiving pull requests.

**Comment by gibfahn** [comment] 2017-10-13 09:59
Duplicate of https://github.com/RuntimeTools/appmetrics/issues/438? Seems like there's some more info there.

**Comment by rwalle61** [comment] 2019-06-10 08:51
As far as we know, the latest master build of Appmetrics should build on Alpine now. See  https://github.com/RuntimeTools/appmetrics/issues/582#issuecomment-499808864.

**Comment by rhowe-gds** [comment] 2019-07-13 17:01
I think we're close..

```
../omr-agentcore/src/ibmras/common/port/linux/Thread.cpp: In function 'void ibmras::common::port::stopAllThreads()':
../omr-agentcore/src/ibmras/common/port/linux/Thread.cpp:144:8: error: 'pthread_getname_np' was not declared in this scope
   rc = pthread_getname_np(top, theName, 16);
        ^~~~~~~~~~~~~~~~~~
```

Introduced by commit 7b11cfe5a7526acb022388fc04148b788ab6ef7d, but `pthread_getname_np` is not available in musl libc (only setname)

**Comment by mattcolegate** [comment] 2019-09-19 13:17
OK, that's fixed and out on npm - Appmetrics 5.0.5 works on Alpine. Any problems, raise an issue!

**Closed by mattcolegate** 2019-09-19 13:17 UTC
Labels: enhancement, help wanted

**Comment by kosmjon** [comment] 2019-10-07 20:35
Thank you very much for this fix!
