### ISSUE TITLE
'request' event data contains duplicated inbound http request

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#390] opened 2017-02-17 03:11 UTC
We have an application monitored by appmetrics 2.0.1, the test request is as following:

User use: /rest/api/getAllPets to request data, application send a http://localhost:4001/api/pets request to query and return the result to user.

As the request event data cannot be stringified. I write logs to print its content iterate.
********** request event data ********** is the event data itself. 
data.request is included in ********** request event data ********** section, so we don't print it separately.
********** children of request event data ********** is each child in children and iterate.

we can see, request id=4 and request id=5 both have type=HTTP. But they are all means to /rest/api/getAllPets. They are duplicated. And actually, request id=5 don't have much meaningful context like request id=4. 
request id=6 is correct, because it is the HTTP Outbound request, which call http://localhost:4001/api/pets. 

```
[2017-02-14 01:21:06.939] [ERROR] knj_log - ********** request event data **********
[2017-02-14 01:21:06.940] [ERROR] knj_log - { time: 1487056866913,
  type: 'HTTP',
  name: '/rest/api/getAllPets',
  duration: 24.483617,
  request:
   Request {
     children: [ [Object] ],
     name: '/rest/api/getAllPets',
     type: 'HTTP',
     parent: undefined,
     id: 4,
     top: [Circular],
     timer:
      Timer {
        startTime: [Object],
        startTimeMillis: 1487056866913,
        timeDelta: 24.483617,
        cpuTimeDelta: -1 },
     active: false,
     tracedStart: true,
     context: { url: '/rest/api/getAllPets' },
     traceStopped: true,
     stack: 'Error\nat ServerResponse.res.end(/root/JanDemo/http_app/node_modules/connect/lib/middleware/logger.js:149)\nat ServerResponse.module.exports [as send](/root/JanDemo/http_app/node_modules/response-send/lib/response-send.js:108)\nat IncomingMessage.<anonymous>(/root/JanDemo/http_app/index.js:74)\nat <module>.emitOne(events.js:96)\nat IncomingMessage.emit(events.js:188)\nat IncomingMessage.Readable.read(_stream_readable.js:381)\nat <module>.flow(_stream_readable.js:761)\nat <module>.resume_(_stream_readable.js:743)\nat <module>._combinedTickCallback(internal/process/next_tick.js:74)' } }
     
[2017-02-14 01:21:06.948] [ERROR] knj_log - ********** children of request event data **********
[2017-02-14 01:21:06.948] [ERROR] knj_log - name: request
[2017-02-14 01:21:06.949] [ERROR] knj_log - type: HTTP
[2017-02-14 01:21:06.949] [ERROR] knj_log - id: 5
[2017-02-14 01:21:06.949] [ERROR] knj_log - Error
at <module>.callbacks(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:165)
at <module>.param(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:139)
at <module>.pass(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:146)
at Router._dispatch(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:173)
at Object.router(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:33)
at <module>.next(/root/JanDemo/http_app/node_modules/connect/lib/proto.js:190)
at Object.cookieParser [as handle](/root/JanDemo/http_app/node_modules/connect/lib/middleware/cookieParser.js:60)
at <module>.next(/root/JanDemo/http_app/node_modules/connect/lib/proto.js:190)
at Object.methodOverride [as handle](/root/JanDemo/http_app/node_modules/connect/lib/middleware/methodOverride.js:37)
[2017-02-14 01:21:06.950] [ERROR] knj_log - Timer {
  startTime: [ 9787573, 526364099 ],
  startTimeMillis: 1487056866919,
  timeDelta: 2.760739,
  cpuTimeDelta: -1 }
  
[2017-02-14 01:21:06.951] [ERROR] knj_log - ********** children of request event data **********
[2017-02-14 01:21:06.951] [ERROR] knj_log - http://localhost:4001/api/pets
[2017-02-14 01:21:06.951] [ERROR] knj_log - HTTP Outbound
[2017-02-14 01:21:06.952] [ERROR] knj_log - 6
[2017-02-14 01:21:06.952] [ERROR] knj_log - Error
    at Array.forEach (native)
at <module>.callbacks(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:165)
at <module>.param(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:139)
at <module>.pass(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:146)
at Router._dispatch(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:173)
at Object.router(/root/JanDemo/http_app/node_modules/express/lib/router/index.js:33)
at <module>.next(/root/JanDemo/http_app/node_modules/connect/lib/proto.js:190)
[2017-02-14 01:21:06.952] [ERROR] knj_log - Timer {
  startTime: [ 9787573, 527096606 ],
  startTimeMillis: 1487056866920,
  timeDelta: 2.265243,
  cpuTimeDelta: -1 }
```

**Comment by ravigadekarla** [comment] 2017-02-17 06:24
To add to what xiaoshimimi mentioned, the issue here is that there are two top level HTTP request events within one Top level Http Request (id:4 and id:5). id:4 request type is HTTP but id:5 request which appears as a nested request also has a type HTTP and and not Http Outbound. How can we have have two HTTP inbound requests as part of one request? So we think id:5 should not be part of the request event. If it's an outbound http call, then it's request type must be HTTP Outbound. We want to better understand is this (id:5)  an issue with data or by design?

**Comment by mattcolegate** [comment] 2017-02-21 16:19
The embedded child request is not a duplicate of the parent request.
- it has a different id value (5 vs 4)
- it has a different name (request vs /rest/api/getAllPets)
- the contents of 5's Error do not match the contents of 4's stack. 

In fact the only thing they have in common is that they are of type HTTP.
5 is not a top-level HTTP request as it's name is not in the form of a path. It looks like a method name.

Given the test code you're running has many many errors, my theory is that something in the request method of 4 caused an error to occur and 5 has been created by our metrics as the error propagates back up the stack. 

@xiaoshimimi , @ravigadekarla Can you please fix your test application so that it doesn't emit errors and retest.

**Comment by mattcolegate** [comment] 2017-02-22 09:44
@xiaoshimimi , @ravigadekarla, please respond.

**Comment by xiaoshimimi** [comment] 2017-02-23 02:24
yes, all three point means 5, 4 are different, but they are all marked as "HTTP" type. actually only 4 is "HTTP" type, 5 should not be.

**Comment by sjanuary** [comment] 2017-02-27 13:42
@xiaoshimimi could you post your test application or a small test case so we can reproduce please?

**Comment by xiaoshimimi** [comment] 2017-03-02 02:25
[outbound-http.zip](https://github.com/RuntimeTools/appmetrics/files/715839/outbound-http.zip), please also reference [issue 365](https://github.com/RuntimeTools/appmetrics/issues/365) for basic usage.

**Comment by sjanuary** [comment] 2017-03-06 11:19
@xiaoshimimi it took us quite a while to reproduce this, e.g. your test case package.json was requiring appmetrics 1.0.11 and we had to change port and hostname in the sample-rest-api project.  We also didn't see the same debug printed out as you and we had to add in the children. I don't think you can have sent us the test case you were actually running?  We have now reproduced it though after those changes

**Comment by mattcolegate** [comment] 2017-03-06 13:32
Thanks very much to @sjanuary for sorting out the problems with the sent test application! We've narrowed the culprit down to the Express probe. I'll put up a PR changing the type it emits to 'Express' but we're not sure if that's the right value - will get @seabaylea to review.

**Comment by tobespc** [comment] 2017-03-13 14:44
Lets remove the express probe as it doesn't provide any value right now

**Closed** 2017-03-15 09:52 UTC
Labels: enhancement
