### ISSUE TITLE
problem with appmetrics while installing module apiconnect-collective-member

### ISSUE THREAD

**Issue by JoelGauci** [RuntimeTools/appmetrics#178] opened 2016-03-31 17:11 UTC
Here is the error stack (cf. the npm-debug.log.zip for more details):
...
[npm-debug.log.zip](https://github.com/RuntimeTools/appmetrics/files/198184/npm-debug.log.zip)

23547 verbose pkgid appmetrics@1.0.7
23548 verbose cwd /usr/local/lib/node_modules
23549 error Linux 3.13.0-57-generic
23550 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "apiconnect-collective-member"
23551 error node v5.8.0
23552 error npm  v3.7.3
23553 error code ELIFECYCLE
23554 error appmetrics@1.0.7 install: `node download_all_binaries.js`
23554 error Exit status 1
23555 error Failed at the appmetrics@1.0.7 install script 'node download_all_binaries.js'.
23555 error Make sure you have the latest version of node.js and npm installed.
23555 error If you do, this is most likely a problem with the appmetrics package,
23555 error not with npm itself.
23555 error Tell the author that this fails on your system:
23555 error     node download_all_binaries.js
23555 error You can get information on how to open an issue for this project with:
23555 error     npm bugs appmetrics
23555 error Or if that isn't available, you can get their info via:
23555 error     npm owner ls appmetrics
23555 error There is likely additional logging output above.
23556 verbose exit [ 1, true ]
****
Thanks for your help,
Joel

**Comment by DanCunnington** [comment] 2016-04-01 08:18
Hi Joel, 

We currently don't support installing appmetrics with node v5 from npm, we are working on this under #138 . We hope to have a release on npm with node v5 support very shortly. In the mean time, you can modify the package.json file to install from GitHub:

```
"dependencies" {
"appmetrics": "RuntimeTools/appmetrics"
}
```

Thanks

**Comment by JoelGauci** [comment] 2016-04-01 12:32
Hello Dan,
I succeeded in installing it with node v4
Thanks 

Joel Gauci
+33621010039

**Comment by hhellyer** [comment] 2016-04-01 13:04
I'll close this as it's already covered by open issue #109 (Issue #138 was already closed as a duplicate of #109)

**Closed by hhellyer** 2016-04-01 13:04 UTC
